export type ParkCatalogEntry = {
  name: string;
  state: string;
  slug: string;
};

export const PARK_CATALOG: ParkCatalogEntry[] = [
  { name: 'Acadia', state: 'ME', slug: 'acadia' },
  { name: 'Arches', state: 'UT', slug: 'arches' },
  { name: 'Badlands', state: 'SD', slug: 'badlands' },
  { name: 'Big Bend', state: 'TX', slug: 'big-bend' },
  { name: 'Biscayne', state: 'FL', slug: 'biscayne' },
  { name: 'Black Canyon of the Gunnison', state: 'CO', slug: 'black-canyon-of-the-gunnison' },
  { name: 'Bryce Canyon', state: 'UT', slug: 'bryce-canyon' },
  { name: 'Canyonlands', state: 'UT', slug: 'canyonlands' },
  { name: 'Capitol Reef', state: 'UT', slug: 'capitol-reef' },
  { name: 'Carlsbad Caverns', state: 'NM', slug: 'carlsbad-caverns' },
  { name: 'Channel Islands', state: 'CA', slug: 'channel-islands' },
  { name: 'Congaree', state: 'SC', slug: 'congaree' },
  { name: 'Crater Lake', state: 'OR', slug: 'crater-lake' },
  { name: 'Cuyahoga Valley', state: 'OH', slug: 'cuyahoga-valley' },
  { name: 'Death Valley', state: 'CA, NV', slug: 'death-valley' },
  { name: 'Denali', state: 'AK', slug: 'denali' },
  { name: 'Dry Tortugas', state: 'FL', slug: 'dry-tortugas' },
  { name: 'Everglades', state: 'FL', slug: 'everglades' },
  { name: 'Gates of the Arctic', state: 'AK', slug: 'gates-of-the-arctic' },
  { name: 'Gateway Arch', state: 'MO', slug: 'gateway-arch' },
  { name: 'Glacier', state: 'MT', slug: 'glacier' },
  { name: 'Glacier Bay', state: 'AK', slug: 'glacier-bay' },
  { name: 'Grand Canyon', state: 'AZ', slug: 'grand-canyon' },
  { name: 'Grand Teton', state: 'WY', slug: 'grand-teton' },
  { name: 'Great Basin', state: 'NV', slug: 'great-basin' },
  { name: 'Great Sand Dunes', state: 'CO', slug: 'great-sand-dunes' },
  { name: 'Great Smoky Mountains', state: 'NC, TN', slug: 'great-smoky-mountains' },
  { name: 'Guadalupe Mountains', state: 'TX', slug: 'guadalupe-mountains' },
  { name: 'Haleakala', state: 'HI', slug: 'haleakala' },
  { name: 'Hawaii Volcanoes', state: 'HI', slug: 'hawaii-volcanoes' },
  { name: 'Indiana Dunes', state: 'IN', slug: 'indiana-dunes' },
  { name: 'Isle Royale', state: 'MI', slug: 'isle-royale' },
  { name: 'Joshua Tree', state: 'CA', slug: 'joshua-tree' },
  { name: 'Katmai', state: 'AK', slug: 'katmai' },
  { name: 'Kenai Fjords', state: 'AK', slug: 'kenai-fjords' },
  { name: 'Kings Canyon', state: 'CA', slug: 'kings-canyon' },
  { name: 'Kobuk Valley', state: 'AK', slug: 'kobuk-valley' },
  { name: 'Lake Clark', state: 'AK', slug: 'lake-clark' },
  { name: 'Lassen Volcanic', state: 'CA', slug: 'lassen-volcanic' },
  { name: 'Mammoth Cave', state: 'KY', slug: 'mammoth-cave' },
  { name: 'Mesa Verde', state: 'CO', slug: 'mesa-verde' },
  { name: 'Mount Rainier', state: 'WA', slug: 'mount-rainier' },
  { name: 'National Park of American Samoa', state: 'AS', slug: 'american-samoa' },
  { name: 'North Cascades', state: 'WA', slug: 'north-cascades' },
  { name: 'Olympic', state: 'WA', slug: 'olympic' },
  { name: 'Petrified Forest', state: 'AZ', slug: 'petrified-forest' },
  { name: 'Pinnacles', state: 'CA', slug: 'pinnacles' },
  { name: 'Redwood', state: 'CA', slug: 'redwood' },
  { name: 'Rocky Mountain', state: 'CO', slug: 'rocky-mountain' },
  { name: 'Saguaro', state: 'AZ', slug: 'saguaro' },
  { name: 'Sequoia', state: 'CA', slug: 'sequoia' },
  { name: 'Shenandoah', state: 'VA', slug: 'shenandoah' },
  { name: 'Theodore Roosevelt', state: 'ND', slug: 'theodore-roosevelt' },
  { name: 'Virgin Islands', state: 'VI', slug: 'virgin-islands' },
  { name: 'Voyageurs', state: 'MN', slug: 'voyageurs' },
  { name: 'White Sands', state: 'NM', slug: 'white-sands' },
  { name: 'Wind Cave', state: 'SD', slug: 'wind-cave' },
  { name: 'Wrangell-St. Elias', state: 'AK', slug: 'wrangell-st-elias' },
  { name: 'Yellowstone', state: 'WY, MT, ID', slug: 'yellowstone' },
  { name: 'Yosemite', state: 'CA', slug: 'yosemite' },
  { name: 'Zion', state: 'UT', slug: 'zion' },
];
