export type ParkCatalogEntry = {
  name: string;
  state: string;
  slug: string;
};

export const PARK_CATALOG: ParkCatalogEntry[] = [
  { name: 'Acadia', state: 'Maine', slug: 'acadia' },
  { name: 'Arches', state: 'Utah', slug: 'arches' },
  { name: 'Badlands', state: 'South Dakota', slug: 'badlands' },
  { name: 'Big Bend', state: 'Texas', slug: 'big-bend' },
  { name: 'Biscayne', state: 'Florida', slug: 'biscayne' },
  { name: 'Black Canyon of the Gunnison', state: 'Colorado', slug: 'black-canyon-of-the-gunnison' },
  { name: 'Bryce Canyon', state: 'Utah', slug: 'bryce-canyon' },
  { name: 'Canyonlands', state: 'Utah', slug: 'canyonlands' },
  { name: 'Capitol Reef', state: 'Utah', slug: 'capitol-reef' },
  { name: 'Carlsbad Caverns', state: 'New Mexico', slug: 'carlsbad-caverns' },
  { name: 'Channel Islands', state: 'California', slug: 'channel-islands' },
  { name: 'Congaree', state: 'South Carolina', slug: 'congaree' },
  { name: 'Crater Lake', state: 'Oregon', slug: 'crater-lake' },
  { name: 'Cuyahoga Valley', state: 'Ohio', slug: 'cuyahoga-valley' },
  { name: 'Death Valley', state: 'California, Nevada', slug: 'death-valley' },
  { name: 'Denali', state: 'Alaska', slug: 'denali' },
  { name: 'Dry Tortugas', state: 'Florida', slug: 'dry-tortugas' },
  { name: 'Everglades', state: 'Florida', slug: 'everglades' },
  { name: 'Gates of the Arctic', state: 'Alaska', slug: 'gates-of-the-arctic' },
  { name: 'Gateway Arch', state: 'Missouri', slug: 'gateway-arch' },
  { name: 'Glacier', state: 'Montana', slug: 'glacier' },
  { name: 'Glacier Bay', state: 'Alaska', slug: 'glacier-bay' },
  { name: 'Grand Canyon', state: 'Arizona', slug: 'grand-canyon' },
  { name: 'Grand Teton', state: 'Wyoming', slug: 'grand-teton' },
  { name: 'Great Basin', state: 'Nevada', slug: 'great-basin' },
  { name: 'Great Sand Dunes', state: 'Colorado', slug: 'great-sand-dunes' },
  { name: 'Great Smoky Mountains', state: 'North Carolina, Tennessee', slug: 'great-smoky-mountains' },
  { name: 'Guadalupe Mountains', state: 'Texas', slug: 'guadalupe-mountains' },
  { name: 'Haleakala', state: 'Hawaii', slug: 'haleakala' },
  { name: 'Hawaii Volcanoes', state: 'Hawaii', slug: 'hawaii-volcanoes' },
  { name: 'Hot Springs', state: 'Arkansas', slug: 'hot-springs' },
  { name: 'Indiana Dunes', state: 'Indiana', slug: 'indiana-dunes' },
  { name: 'Isle Royale', state: 'Michigan', slug: 'isle-royale' },
  { name: 'Joshua Tree', state: 'California', slug: 'joshua-tree' },
  { name: 'Katmai', state: 'Alaska', slug: 'katmai' },
  { name: 'Kenai Fjords', state: 'Alaska', slug: 'kenai-fjords' },
  { name: 'Kings Canyon', state: 'California', slug: 'kings-canyon' },
  { name: 'Kobuk Valley', state: 'Alaska', slug: 'kobuk-valley' },
  { name: 'Lake Clark', state: 'Alaska', slug: 'lake-clark' },
  { name: 'Lassen Volcanic', state: 'California', slug: 'lassen-volcanic' },
  { name: 'Mammoth Cave', state: 'Kentucky', slug: 'mammoth-cave' },
  { name: 'Mesa Verde', state: 'Colorado', slug: 'mesa-verde' },
  { name: 'Mount Rainier', state: 'Washington', slug: 'mount-rainier' },
  { name: 'National Park of American Samoa', state: 'American Samoa', slug: 'american-samoa' },
  { name: 'North Cascades', state: 'Washington', slug: 'north-cascades' },
  { name: 'Olympic', state: 'Washington', slug: 'olympic' },
  { name: 'Petrified Forest', state: 'Arizona', slug: 'petrified-forest' },
  { name: 'Pinnacles', state: 'California', slug: 'pinnacles' },
  { name: 'Redwood', state: 'California', slug: 'redwood' },
  { name: 'Rocky Mountain', state: 'Colorado', slug: 'rocky-mountain' },
  { name: 'Saguaro', state: 'Arizona', slug: 'saguaro' },
  { name: 'Sequoia', state: 'California', slug: 'sequoia' },
  { name: 'Shenandoah', state: 'Virginia', slug: 'shenandoah' },
  { name: 'Theodore Roosevelt', state: 'North Dakota', slug: 'theodore-roosevelt' },
  { name: 'Virgin Islands', state: 'U.S. Virgin Islands', slug: 'virgin-islands' },
  { name: 'Voyageurs', state: 'Minnesota', slug: 'voyageurs' },
  { name: 'White Sands', state: 'New Mexico', slug: 'white-sands' },
  { name: 'Wind Cave', state: 'South Dakota', slug: 'wind-cave' },
  { name: 'Wrangell-St. Elias', state: 'Alaska', slug: 'wrangell-st-elias' },
  { name: 'Yellowstone', state: 'Idaho, Montana, Wyoming', slug: 'yellowstone' },
  { name: 'Yosemite', state: 'California', slug: 'yosemite' },
  { name: 'Zion', state: 'Utah', slug: 'zion' },
];
