from __future__ import annotations

PARKS = [
    {"name": "Acadia", "slug": "acadia", "park_code": "acad", "state": "Maine"},
    {"name": "Arches", "slug": "arches", "park_code": "arch", "state": "Utah"},
    {"name": "Badlands", "slug": "badlands", "park_code": "badl", "state": "South Dakota"},
    {"name": "Big Bend", "slug": "big-bend", "park_code": "bibe", "state": "Texas"},
    {"name": "Biscayne", "slug": "biscayne", "park_code": "bisc", "state": "Florida"},
    {"name": "Black Canyon of the Gunnison", "slug": "black-canyon-of-the-gunnison", "park_code": "blca", "state": "Colorado"},
    {"name": "Bryce Canyon", "slug": "bryce-canyon", "park_code": "brca", "state": "Utah"},
    {"name": "Canyonlands", "slug": "canyonlands", "park_code": "cany", "state": "Utah"},
    {"name": "Capitol Reef", "slug": "capitol-reef", "park_code": "care", "state": "Utah"},
    {"name": "Carlsbad Caverns", "slug": "carlsbad-caverns", "park_code": "cave", "state": "New Mexico"},
    {"name": "Channel Islands", "slug": "channel-islands", "park_code": "chis", "state": "California"},
    {"name": "Congaree", "slug": "congaree", "park_code": "cong", "state": "South Carolina"},
    {"name": "Crater Lake", "slug": "crater-lake", "park_code": "crla", "state": "Oregon"},
    {"name": "Cuyahoga Valley", "slug": "cuyahoga-valley", "park_code": "cuva", "state": "Ohio"},
    {"name": "Death Valley", "slug": "death-valley", "park_code": "deva", "state": "California, Nevada"},
    {"name": "Denali", "slug": "denali", "park_code": "dena", "state": "Alaska"},
    {"name": "Dry Tortugas", "slug": "dry-tortugas", "park_code": "drto", "state": "Florida"},
    {"name": "Everglades", "slug": "everglades", "park_code": "ever", "state": "Florida"},
    {"name": "Gates of the Arctic", "slug": "gates-of-the-arctic", "park_code": "gaar", "state": "Alaska"},
    {"name": "Gateway Arch", "slug": "gateway-arch", "park_code": "jeff", "state": "Missouri"},
    {"name": "Glacier", "slug": "glacier", "park_code": "glac", "state": "Montana"},
    {"name": "Glacier Bay", "slug": "glacier-bay", "park_code": "glba", "state": "Alaska"},
    {"name": "Grand Canyon", "slug": "grand-canyon", "park_code": "grca", "state": "Arizona"},
    {"name": "Grand Teton", "slug": "grand-teton", "park_code": "grte", "state": "Wyoming"},
    {"name": "Great Basin", "slug": "great-basin", "park_code": "grba", "state": "Nevada"},
    {"name": "Great Sand Dunes", "slug": "great-sand-dunes", "park_code": "grsa", "state": "Colorado"},
    {"name": "Great Smoky Mountains", "slug": "great-smoky-mountains", "park_code": "grsm", "state": "North Carolina, Tennessee"},
    {"name": "Guadalupe Mountains", "slug": "guadalupe-mountains", "park_code": "gumo", "state": "Texas"},
    {"name": "Haleakala", "slug": "haleakala", "park_code": "hale", "state": "Hawaii"},
    {"name": "Hawaii Volcanoes", "slug": "hawaii-volcanoes", "park_code": "havo", "state": "Hawaii"},
    {"name": "Hot Springs", "slug": "hot-springs", "park_code": "hosp", "state": "Arkansas"},
    {"name": "Indiana Dunes", "slug": "indiana-dunes", "park_code": "indu", "state": "Indiana"},
    {"name": "Isle Royale", "slug": "isle-royale", "park_code": "isro", "state": "Michigan"},
    {"name": "Joshua Tree", "slug": "joshua-tree", "park_code": "jotr", "state": "California"},
    {"name": "Katmai", "slug": "katmai", "park_code": "katm", "state": "Alaska"},
    {"name": "Kenai Fjords", "slug": "kenai-fjords", "park_code": "kefj", "state": "Alaska"},
    {"name": "Kings Canyon", "slug": "kings-canyon", "park_code": "kica", "state": "California"},
    {"name": "Kobuk Valley", "slug": "kobuk-valley", "park_code": "kova", "state": "Alaska"},
    {"name": "Lake Clark", "slug": "lake-clark", "park_code": "lacl", "state": "Alaska"},
    {"name": "Lassen Volcanic", "slug": "lassen-volcanic", "park_code": "lavo", "state": "California"},
    {"name": "Mammoth Cave", "slug": "mammoth-cave", "park_code": "maca", "state": "Kentucky"},
    {"name": "Mesa Verde", "slug": "mesa-verde", "park_code": "meve", "state": "Colorado"},
    {"name": "Mount Rainier", "slug": "mount-rainier", "park_code": "mora", "state": "Washington"},
    {"name": "National Park of American Samoa", "slug": "american-samoa", "park_code": "npsa", "state": "American Samoa"},
    {"name": "New River Gorge", "slug": "new-river-gorge", "park_code": "neri", "state": "West Virginia"},
    {"name": "North Cascades", "slug": "north-cascades", "park_code": "noca", "state": "Washington"},
    {"name": "Olympic", "slug": "olympic", "park_code": "olym", "state": "Washington"},
    {"name": "Petrified Forest", "slug": "petrified-forest", "park_code": "pefo", "state": "Arizona"},
    {"name": "Pinnacles", "slug": "pinnacles", "park_code": "pinn", "state": "California"},
    {"name": "Redwood", "slug": "redwood", "park_code": "redw", "state": "California"},
    {"name": "Rocky Mountain", "slug": "rocky-mountain", "park_code": "romo", "state": "Colorado"},
    {"name": "Saguaro", "slug": "saguaro", "park_code": "sagu", "state": "Arizona"},
    {"name": "Sequoia", "slug": "sequoia", "park_code": "seki", "state": "California"},
    {"name": "Shenandoah", "slug": "shenandoah", "park_code": "shen", "state": "Virginia"},
    {"name": "Theodore Roosevelt", "slug": "theodore-roosevelt", "park_code": "thro", "state": "North Dakota"},
    {"name": "Virgin Islands", "slug": "virgin-islands", "park_code": "viis", "state": "U.S. Virgin Islands"},
    {"name": "Voyageurs", "slug": "voyageurs", "park_code": "voya", "state": "Minnesota"},
    {"name": "White Sands", "slug": "white-sands", "park_code": "whsa", "state": "New Mexico"},
    {"name": "Wind Cave", "slug": "wind-cave", "park_code": "wica", "state": "South Dakota"},
    {"name": "Wrangell-St. Elias", "slug": "wrangell-st-elias", "park_code": "wrst", "state": "Alaska"},
    {"name": "Yellowstone", "slug": "yellowstone", "park_code": "yell", "state": "Idaho, Montana, Wyoming"},
    {"name": "Yosemite", "slug": "yosemite", "park_code": "yose", "state": "California"},
    {"name": "Zion", "slug": "zion", "park_code": "zion", "state": "Utah"},
]

PARKS_BY_SLUG = {park["slug"]: park for park in PARKS}
